import "./globals.css";
import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import { classNames } from "@/lib";
import { Menu } from "@/components";
import { MobileMenu } from "@/components/MobileMenu";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "StorySpark ✨",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(fredoka.className, "bg-palette-page")}>
        <Menu />
        <MobileMenu />
        {children}
        <footer>
          <span className="flex items-center justify-center text-center text-sm leading-5 ">
            &copy; {new Date().getFullYear()} | Developed by Alice Anglesjö
          </span>
        </footer>
      </body>
    </html>
  );
}
