import "./globals.css";
import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import { classNames } from "@/lib";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={classNames(fredoka.className, "bg-palette-page")}>
        {children}
      </body>
    </html>
  );
}
